### ISSUE TITLE
Difference with official code - utils.MentorNet.forwawrd

### ISSUE THREAD

**Issue by Schmerle-Cki** [Furyton/MentorNet_pytorch#1]
Hello, thanks for your reproduction! In utils.py, line 144, `upper_bound = torch.where(cur_epoch < burn_in_epoch - 1, v_zeros, v_ones).to(self.device)`, while in google_mentornet, codes accordingly in [utils.py](https://github.com/google/mentornet/blob/master/code/utils.py), line 211-212,  `upper_bound = tf.cond(cur_epoch < (burn_in_epoch - 1), lambda: v_ones, lambda: v_zeros)`. The order of `v_ones` and `v_zeros` seems to be a conflict. Is there a typo, or maybe I have misunderstood some of your definitions？

**Comment by Furyton** [comment]
Hi, I'm afraid that is indeed a typo. I fixed it in another private repo and forgot to update it here :(
I have fixed it just now. Thank you for your reporting. :)
